### ISSUE TITLE
cannot download the plugin correctly

### ISSUE THREAD

**Issue by lightsrage** [AardCrowley/Search-and-Destroy#1]
Hello i tried to download this via save link as and cannot get a propper looking mush client plugin page to come up it shows me web stuff and how to add comments to lines and such but not how to download the entire latest plugin perhapse some download instructions would be handy. decided to put this up as an issue because I did not know what else to do.

**Comment by AardCrowley** [comment]
That's because you're not supposed to right-click and choose "Save as..." because it saves it as a web page (despite it being an .xml file). Instead, there's a green "Code" button you need to click and you can download the entire .zip file. Then you can extract the file that way.

Let me know if you have any other issues with it!
